#!/bin/sh

if [ $# -ne 1 ]; then
    echo "usage: $0 [UseCaseName]"
    exit 1
fi

use_case=$1
use_case_path="ReelTime-iOS/UseCase/$use_case"

mkdir -p "$use_case_path/Assembly"
mkdir -p "$use_case_path/Domain"
mkdir -p "$use_case_path/Navigation"
mkdir -p "$use_case_path/Persistence"
mkdir -p "$use_case_path/Presentation"

echo "created directory structure for $use_case"
